"""Update Profile field nullable state

Revision ID: c9a6d63f0ada
Revises: e22a80df70d2
Create Date: 2024-06-21 21:09:24.303104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a6d63f0ada'
down_revision: Union[str, None] = 'e22a80df70d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'role',
               existing_type=postgresql.ENUM('user', 'moderator', 'admin', name='roleenum'),
               nullable=True)
    op.alter_column('profile', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=True)
    op.alter_column('profile', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('profile', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('profile', 'country',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('profile', 'personality',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'personality',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('profile', 'country',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('profile', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('profile', 'visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('profile', 'description',
               existing_type=sa.VARCHAR(length=600),
               nullable=False)
    op.alter_column('profile', 'role',
               existing_type=postgresql.ENUM('user', 'moderator', 'admin', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###
