"""Init

Revision ID: e144f942e467
Revises: 
Create Date: 2024-08-24 19:37:45.652245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.utils import JSONEncodedList


# revision identifiers, used by Alembic.
revision: str = 'e144f942e467'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('displayName', sa.String(length=255), nullable=False),
    sa.Column('telegram', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='roleenum'), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('translation', 'fill_in', 'multiple_choice', 'matching', 'rearrange', name='tasktypeenum'), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('options', JSONEncodedList(), nullable=True),
    sa.Column('answer', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('sentence', sa.String(), nullable=True),
    sa.Column('pairs', JSONEncodedList(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('lesson')
    op.drop_table('profile')
    # ### end Alembic commands ###
