"""Add Lesson model

Revision ID: ec2e25793be6
Revises: 0b09e51669d7
Create Date: 2024-07-30 17:59:30.907182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec2e25793be6'
down_revision: Union[str, None] = '0b09e51669d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language_studied', sa.Enum('en', 'de', name='studiedlanguageenum'), nullable=False),
    sa.Column('interface_language', sa.Enum('ru', 'uk', name='interfacelanguageenum'), nullable=False),
    sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
